services:

  db:
    container_name: is-db
    build: docker/images/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  
  redis:
    container_name: is-redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  rpc-server:
    container_name: is-rpc-server
    build: docker/images/python
    volumes:
      - "./src/rpc-server:/app"
      - "./docker/volumes/data:/data"
    ports:
      - 9000:9000
    depends_on:
      - db
      - redis

  rpc-client:
    container_name: is-rpc-client
    build: docker/images/python
    volumes:
      - "./src/rpc-client:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server
    command: ["python", "main.py"]

volumes:
  postgres_data: